### ISSUE TITLE
[Feature Request] endpoint to do HEALTHCHECK on docker

### ISSUE THREAD

**Issue by garzy** [JPro-one/JPro-tickets#101]
Please fix [this issue](https://github.com/JPro-one/JPro-tickets/issues/92) or add an endpoint in JPro server to check if the server is healthy and running ok because I need to know when to force recreate the container.

**Comment by FlorianKirmaier** [comment]
Try this: https://<your-server>/status/alive

**Comment by garzy** [comment]
OK, thanks for the trick.
I've added this to my docker-compose.yml file and it's working:

```yml
healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/status/alive"]
      interval: 1m30s
      timeout: 10s
      retries: 3
```
